# Generated by Django 3.2.6 on 2021-10-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service categories'},
        ),
    ]
