# Generated by Django 3.2.6 on 2021-10-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211006_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='article',
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
