# Generated by Django 3.2.6 on 2021-10-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_state_slug'),
        ('cities', '0012_auto_20211005_1347'),
        ('services', '0005_servicereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='states.state'),
        ),
    ]
