# Generated by Django 3.2.6 on 2021-10-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_seoservicearticle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
