# Generated by Django 3.2.6 on 2021-08-31 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('employees', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.state'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
