# Generated by Django 3.2.6 on 2021-09-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_alter_thirdscreen_image'),
        ('employees', '0006_alter_employee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='states.state'),
        ),
    ]
