# Generated by Django 3.2.6 on 2021-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='count_votes',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
