# Generated by Django 3.2.6 on 2021-10-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
        ('employees', '0008_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='count_votes',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SEOEmployee',
            fields=[
                ('seobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.seobase')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
            bases=('seo.seobase',),
        ),
    ]
