# Generated by Django 3.2.6 on 2021-10-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20211012_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
