# Generated by Django 3.2.6 on 2021-08-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_paragraphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='image',
            field=models.ImageField(default='default-picture.png', null=True, upload_to='articles/par/'),
        ),
    ]
