# Generated by Django 3.2.6 on 2021-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_paragraphs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/par/'),
        ),
    ]
