# Generated by Django 3.2.6 on 2021-08-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_paragraphs_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleViews',
            new_name='ArticleView',
        ),
    ]
