# Generated by Django 3.2.6 on 2021-08-28 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210828_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2b799721-07db-11ec-95ee-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
