# Generated by Django 3.2.6 on 2021-08-28 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerating',
            name='user',
        ),
        migrations.AddField(
            model_name='articlerating',
            name='IPAddress',
            field=models.GenericIPAddressField(default='45.243.82.169'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fcc2e228-07e1-11ec-b81b-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
