# Generated by Django 3.2.6 on 2021-08-28 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210828_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='quote',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d440ce01-07e7-11ec-9349-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
