# Generated by Django 3.2.6 on 2021-08-28 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210828_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraphs',
            options={'verbose_name_plural': 'Paragraphs'},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f4a07223-07ec-11ec-8783-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paragraphs',
            name='quote',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paragraphs',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
