# Generated by Django 3.2.6 on 2021-08-28 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20210828_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2a9339aa-07ed-11ec-a677-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
