# Generated by Django 3.2.6 on 2021-08-28 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('59ce0584-07ed-11ec-aad9-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
