# Generated by Django 3.2.6 on 2021-08-30 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a68de472-0964-11ec-aec7-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
