# Generated by Django 3.2.6 on 2021-08-31 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a8463240-0a3a-11ec-b943-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
