# Generated by Django 3.2.6 on 2021-08-31 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5555ca2d-0a3b-11ec-ad9d-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
