# Generated by Django 3.2.6 on 2021-08-31 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d4ed684e-0a3c-11ec-95ed-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
