# Generated by Django 3.2.6 on 2021-08-31 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7ae865af-0a3d-11ec-af8d-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
