# Generated by Django 3.2.6 on 2021-08-31 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f77492f6-0a41-11ec-aa13-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
