# Generated by Django 3.2.6 on 2021-08-31 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5174ab43-0a4b-11ec-aceb-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
