# Generated by Django 3.2.6 on 2021-08-31 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7ee85840-0a60-11ec-9983-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
