# Generated by Django 3.2.6 on 2021-08-31 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5f1daf93-0a62-11ec-91f8-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
