# Generated by Django 3.2.6 on 2021-09-02 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a3c510f7-0bda-11ec-a06b-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
