# Generated by Django 3.2.6 on 2021-09-02 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f9c6d160-0bf2-11ec-9b5e-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
