# Generated by Django 3.2.6 on 2021-09-02 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4f173360-0bf3-11ec-9284-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
