# Generated by Django 3.2.6 on 2021-09-02 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.UUID('01247bcd-0bf4-11ec-9645-e4a8df898f19'), editable=False, max_length=100, unique=True),
        ),
    ]
