# Generated by Django 3.2.6 on 2021-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
