# Generated by Django 3.2.6 on 2021-10-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
        ('articles', '0040_auto_20211005_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOArticles',
            fields=[
                ('seobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.seobase')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='articles.article')),
            ],
            bases=('seo.seobase',),
        ),
    ]
