# Generated by Django 3.2.6 on 2021-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('alt', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
