# Generated by Django 3.2.6 on 2021-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_auto_20210831_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstscreen',
            old_name='city',
            new_name='state',
        ),
    ]
