# Generated by Django 3.2.6 on 2021-08-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_rename_city_firstscreen_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondscreen',
            name='list',
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='states.state'),
        ),
    ]
