# Generated by Django 3.2.6 on 2021-09-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_auto_20210831_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='states/first_screen/'),
        ),
        migrations.AlterField(
            model_name='thirdscreen',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
    ]
