# Generated by Django 3.2.6 on 2021-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_alter_thirdscreen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='<function uuid1 at 0x000001B24F7591F0><function uuid3 at 0x000001B24F759280>', editable=False, max_length=150, unique=True),
        ),
    ]
