# Generated by Django 3.2.6 on 2021-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_state_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='<function uuid1 at 0x000002538F6E91F0><function uuid3 at 0x000002538F6E9280>', editable=False, max_length=150),
        ),
    ]
