# Generated by Django 3.2.6 on 2021-10-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
        ('states', '0008_state_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOState',
            fields=[
                ('seobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo.seobase')),
                ('state', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='states.state')),
            ],
            bases=('seo.seobase',),
        ),
    ]
