# Generated by Django 3.2.6 on 2021-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0009_seostate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seostate',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
