# Generated by Django 3.2.6 on 2021-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0011_auto_20211013_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='states/first_screen/'),
        ),
        migrations.AddField(
            model_name='thirdscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='states/third_screen/'),
        ),
    ]
