# Generated by Django 3.2.6 on 2021-10-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0012_auto_20211013_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstscreen',
            name='image',
        ),
        migrations.RemoveField(
            model_name='thirdscreen',
            name='image',
        ),
    ]
