# Generated by Django 3.2.6 on 2021-10-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('states', '0013_auto_20211018_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreen',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='thirdscreen',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo'),
        ),
    ]
