# Generated by Django 3.2.6 on 2021-08-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='cities/first_screen/')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=250)),
                ('main_description', models.TextField()),
                ('sec_title', models.CharField(max_length=250)),
                ('sec_description', models.TextField()),
                ('thrd_title', models.CharField(max_length=250)),
                ('thrd_description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/third_screen/')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SecondScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=250)),
                ('main_description', models.TextField()),
                ('sec_title', models.CharField(max_length=250)),
                ('sec_description', models.TextField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.paragraphs')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='first_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.firstscreen'),
        ),
        migrations.AddField(
            model_name='city',
            name='second_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.secondscreen'),
        ),
        migrations.AddField(
            model_name='city',
            name='third_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.thirdscreen'),
        ),
        migrations.AddField(
            model_name='state',
            name='first_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.firstscreen'),
        ),
        migrations.AddField(
            model_name='state',
            name='second_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.secondscreen'),
        ),
        migrations.AddField(
            model_name='state',
            name='third_screen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.thirdscreen'),
        ),
    ]
