# Generated by Django 3.2.6 on 2021-08-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20210831_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='first_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.firstscreen'),
        ),
        migrations.AlterField(
            model_name='city',
            name='second_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.secondscreen'),
        ),
        migrations.AlterField(
            model_name='city',
            name='third_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.thirdscreen'),
        ),
        migrations.AlterField(
            model_name='state',
            name='first_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.firstscreen'),
        ),
        migrations.AlterField(
            model_name='state',
            name='second_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.secondscreen'),
        ),
        migrations.AlterField(
            model_name='state',
            name='third_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.thirdscreen'),
        ),
    ]
