# Generated by Django 3.2.6 on 2021-08-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_state'),
        ('states', '0001_initial'),
        ('cities', '0004_auto_20210831_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstscreen',
            options={'verbose_name_plural': 'First Screen'},
        ),
        migrations.AlterModelOptions(
            name='secondscreen',
            options={'verbose_name_plural': 'Second Screen'},
        ),
        migrations.AlterModelOptions(
            name='thirdscreen',
            options={'verbose_name_plural': 'Third Screen'},
        ),
        migrations.RemoveField(
            model_name='firstscreen',
            name='state',
        ),
        migrations.RemoveField(
            model_name='secondscreen',
            name='state',
        ),
        migrations.RemoveField(
            model_name='thirdscreen',
            name='state',
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
