# Generated by Django 3.2.6 on 2021-09-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_auto_20210902_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/first_screen/'),
        ),
        migrations.AlterField(
            model_name='secondscreen',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='thirdscreen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/third_screen/'),
        ),
    ]
