# Generated by Django 3.2.6 on 2021-09-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20210902_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondscreen',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='thirdscreen',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
    ]
