# Generated by Django 3.2.6 on 2021-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_auto_20210902_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
