# Generated by Django 3.2.6 on 2021-09-30 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, editable=False, max_length=150, unique=True),
        ),
    ]
