# Generated by Django 3.2.6 on 2021-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
