# Generated by Django 3.2.6 on 2021-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='<function uuid1 at 0x00000287024091F0><function uuid3 at 0x0000028702409280>', editable=False, max_length=150),
        ),
    ]
