# Generated by Django 3.2.6 on 2021-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_seocity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seocity',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
