# Generated by Django 3.2.6 on 2021-10-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_alter_seocity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstscreen',
            name='image',
        ),
        migrations.RemoveField(
            model_name='thirdscreen',
            name='image',
        ),
    ]
